"""Type stubs for the compiled matrixcore.solvers extension module."""

from typing import Any, Literal, overload

import numpy as np
import numpy.typing as npt

SolverInfo = dict[str, float]

def list_available_solvers() -> list[str]: ...
@overload
def solve_system(
    A: npt.ArrayLike,
    b: npt.ArrayLike,
    method: str = ...,
    return_info: Literal[False] = ...,
) -> np.ndarray: ...
@overload
def solve_system(
    A: npt.ArrayLike,
    b: npt.ArrayLike,
    method: str,
    return_info: Literal[True],
) -> tuple[np.ndarray, SolverInfo]: ...
@overload
def solve_system(
    A: npt.ArrayLike,
    b: npt.ArrayLike,
    method: str = ...,
    *,
    return_info: Literal[True],
) -> tuple[np.ndarray, SolverInfo]: ...

# Convenience per-method wrappers, e.g. lu_decomposition_solver(A, b, return_info=False).
def gaussian_elimination_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def gauss_jordan_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def back_substitution_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def forward_substitution_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def lu_decomposition_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def cholesky_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def qr_decomposition_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def matrix_inversion_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def cramers_rule_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def row_echelon_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def reduced_row_echelon_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def triangularization_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def jacobi_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def gauss_seidel_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def sor_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def conjugate_gradient_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def gradient_descent_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def minres_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def gmres_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def bicg_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def iterative_refinement_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def normal_equations_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def orthogonal_projection_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
def svd_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def pseudoinverse_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def block_matrix_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def partitioning_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def matrix_rank_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def determinant_solver(A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...) -> Any: ...
def eigenvalue_decomposition_solver(
    A: npt.ArrayLike, b: npt.ArrayLike, return_info: bool = ...
) -> Any: ...
